/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.module;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

class SumCalculatorTest {

    private SumCalculator sumCalculator;

    @BeforeEach
    public void beforeEach() {
        sumCalculator = new SumCalculator();
    }

    @Test
    public void testThatSumCalculatorWorksCorrect() {

        Assertions.assertDoesNotThrow(() -> {
            for(int n = 1; n < 65536; n++) {
                sumCalculator.sum(n);
            }
        });

        Assertions.assertThrows(IllegalArgumentException.class, () -> sumCalculator.sum(0));
        Assertions.assertThrows(IllegalArgumentException.class, () -> sumCalculator.sum(-4));
        Assertions.assertThrows(IllegalArgumentException.class, () -> sumCalculator.sum(65536));


    }
}

