/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.module;

import java.math.BigInteger;

public class SumCalculator {
    public int sum(int n) {

        if(checkVarIsCorrect(n)) {
            return n * (n + 1) / 2;
        }
        else throw new IllegalArgumentException();
    }

    private boolean checkVarIsCorrect(int n) {

        if(n * (n + 1l) / 2l <= Integer.MAX_VALUE && n > 0) return true;
        return false;
    }
}
